// All catalog entries, versions and availability are review fixtures, not a registry.
const version = (number, notes, extra = {}) => ({ number, notes, api: 4, date: "2026-09-18", size: "240 KB", ...extra });
export const categories = ["全部", "工具", "语音", "记忆", "连接", "表现"];
export function createPlugins() {
  return [
    { id: "playwright_browser", name: "Playwright 浏览器", author: "Chihiro", category: "工具", kind: "功能扩展", icon: "globe", color: "blue", description: "让 Sakura 打开和操作网页，也能搜索、读取内容和截图。", body: "通过对话浏览网页、填写表单和提取页面内容。截图可作为附件返回对话。", consequence: "启用后可操作网页并访问页面内容。浏览器运行组件需另行下载。", versions: [version("1.0.0", "提供网页浏览、搜索与截图工具。", { size: "428 KB" })] },
    { id: "example.notebook", name: "随手记", author: "Haru", category: "工具", kind: "功能扩展", icon: "sticky-note", color: "gold", example: true, description: "把对话里的灵感和待办记下来，随时找回。", body: "让 Sakura 创建、查找和整理本地笔记。可按标题和内容检索，适合保存临时想法与待办。", consequence: "启用后可读写你指定的笔记文件夹。", versions: [version("1.2.0", "新增笔记标题检索与待办整理。", { date: "2026-09-20", size: "186 KB" }), version("1.1.0", "支持创建和读取笔记。", { date: "2026-09-02" })] },
    { id: "sakura.memory.mem0", name: "Mem0 记忆", author: "Sakura", category: "记忆", kind: "功能引擎", icon: "brain", color: "pink", installed: "1.0.0", enabled: true, description: "记住聊天中值得保留的事情，在之后的对话中想起。", body: "为角色提供长期记忆，支持记忆检索与整理。所需模型和记忆内容在记忆设置中管理。", consequence: "更新期间会暂停此插件；保留现有配置和记忆数据。", versions: [version("0.2.0", "改善记忆整理的状态反馈。", { date: "2026-09-19", size: "312 KB" }), version("0.1.0", "提供长期记忆与检索。", { date: "2026-08-30" })] },
    { id: "sakura_mobile", name: "Sakura Mobile", author: "Sakura", category: "连接", kind: "功能扩展", icon: "smartphone", color: "green", installed: "1.0.0", enabled: true, description: "在手机浏览器里连接 Sakura，继续与你的角色聊天。", body: "提供手机网页入口。监听地址、端口和访问令牌由插件设置管理。", consequence: "启用后会监听网络端口；访问范围取决于监听地址。", versions: [version("1.0.0", "提供手机端对话界面。", { size: "1.8 MB" })] },
    { id: "sakura.tts.genie", name: "Genie TTS", author: "Sakura", category: "语音", kind: "功能引擎", icon: "audio-lines", color: "violet", installed: "1.0.0", bundled: true, enabled: false, description: "为角色合成语音，支持本地运行或连接已有服务。", body: "在语音设置中为角色选择此引擎。使用本地服务时，需要在插件设置中准备运行组件。", consequence: "本地语音组件和音色资源需另行准备。", versions: [version("0.1.0", "支持本地服务与已有服务。", { size: "96 KB" })] },
    { id: "example.mcp", name: "MCP 工具桥", author: "Aoi", category: "连接", kind: "功能扩展", icon: "puzzle", color: "blue", example: true, description: "将已有 MCP 服务中的工具接入 Sakura 对话。", body: "连接你配置的 MCP 服务，并将工具交给角色使用。当前目录推荐与 Plugin API 4 兼容的版本。", consequence: "工具调用可能把对话中相关内容发送到你配置的服务。", versions: [version("2.0.0", "适配新版插件接口。", { api: 5, date: "2026-09-20" }), version("1.4.0", "改善工具参数展示。", { date: "2026-09-12", size: "208 KB" }), version("1.3.0", "工具连接调整。", { yanked: "工具参数映射错误，可能导致调用失败。", date: "2026-09-01" }), version("2.1.0-beta.1", "实验性工具发现。", { api: 5, prerelease: true })] },
    { id: "example.live2d", name: "Live2D 表现", author: "Mizuki", category: "表现", kind: "功能引擎", icon: "user-round", color: "pink", example: true, description: "让角色以 Live2D 模型呈现动作与表情。", body: "为包含 Live2D 资源的角色提供显示能力。当前示例版本要求 Plugin API 5。", consequence: "需要角色包提供对应模型资源。", versions: [version("0.2.0", "提供模型加载与表情切换。", { api: 5, size: "2.6 MB" })] },
    { id: "example.reading", name: "阅读助手", author: "Yuki", category: "工具", kind: "功能扩展", icon: "file-text", color: "green", example: true, description: "提取本地文档内容，和 Sakura 一起阅读与讨论。", body: "选择文档后提取正文，在对话中总结内容或查询细节。", consequence: "选中文档的相关内容可能随对话发送给当前模型服务。", versions: [version("1.0.0", "支持本地文本文档提取。", { size: "164 KB", date: "2026-09-15" })] },
  ];
}
export const recommended = (plugin) => plugin.versions.find(v => v.api === 4 && !v.yanked && !v.prerelease);
