server {
    listen 80;
    server_name adm.sakura.cialloo.cn api.sakura.cialloo.cn;
    location ^~ /.well-known/acme-challenge/ { root /var/lib/sakura-acme; }
    location / { return 301 https://$host$request_uri; }
}
